### ISSUE TITLE
We don't need to write a comment for every single line of code

### ISSUE THREAD

**Issue by afgprogrammer** [oussamabouchikhi/todos-app#4]
We need to think of comments like documentation. It is an expensive artifact that needs to be maintained. Because of this, we should add comments only in a location where it is necessary and the code itself cannot express what is happening there.

so, we should not write unnecessary comments.

https://github.com/oussamabouchikhi/todos-app/blob/5234053a1a5c3d09c21cbc81f07bcc3b868cf8a2/app/Http/Controllers/todosController.php#L62

**Comment by oussamabouchikhi** [comment]
Thank you for the note
